# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from citysim_slurm.models.city_sim_slurm_status import CitySimSlurmStatus

class TestCitySimSlurmStatus(unittest.TestCase):
    """CitySimSlurmStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCitySimSlurmStatus(self):
        """Test CitySimSlurmStatus"""
        # inst = CitySimSlurmStatus()

if __name__ == '__main__':
    unittest.main()
