# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from citysim_slurm.api.default_api import DefaultApi


class TestDefaultApi(unittest.IsolatedAsyncioTestCase):
    """DefaultApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DefaultApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_cancel_cancel_job_id_get(self) -> None:
        """Test case for cancel_cancel_job_id_get

        Cancel
        """
        pass

    async def test_create_create_name_get(self) -> None:
        """Test case for create_create_name_get

        Create
        """
        pass

    async def test_delete_delete_name_get(self) -> None:
        """Test case for delete_delete_name_get

        Delete
        """
        pass

    async def test_health_health_get(self) -> None:
        """Test case for health_health_get

        Health
        """
        pass

    async def test_run_run_name_get(self) -> None:
        """Test case for run_run_name_get

        Run
        """
        pass

    async def test_status_status_job_id_get(self) -> None:
        """Test case for status_status_job_id_get

        Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
