# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CitySimSlurmStatus(str, Enum):
    """
    CitySimSlurmStatus
    """

    """
    allowed enum values
    """
    NONE = 'none'
    HEALTHY = 'healthy'
    CREATED = 'created'
    SUBMITTED = 'submitted'
    RUNNING = 'running'
    COMPLETED = 'completed'
    CANCELLED = 'cancelled'
    DELETED = 'deleted'
    ERROR = 'error'
    DEAD = 'dead'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CitySimSlurmStatus from a JSON string"""
        return cls(json.loads(json_str))


